service:
  port: 8080
  domain: localhost
  endpoint: /api

db:
  postgresDB:
    connection:
      string: port=5432 user=postgres password=password host=localhost dbname=postgres sslmode=disable
      timeout: 25
      max:
        open: 50
        idle: 5
        lifetime: 3
      query:
        timeout: 30
